//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPuTTY.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoPuTTY.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_icon {
            get {
                object obj = ResourceManager.GetObject("blue_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closed {
            get {
                object obj = ResourceManager.GetObject("closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeh {
            get {
                object obj = ResourceManager.GetObject("closeh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string connectionHelper_LaunchVnc_Error {
            get {
                return ResourceManager.GetString("connectionHelper_LaunchVnc_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not find file &quot;.
        /// </summary>
        internal static string connectionHelper_LaunchVnc_M1 {
            get {
                return ResourceManager.GetString("connectionHelper_LaunchVnc_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;.
        ///Do you want to change the configuration ?.
        /// </summary>
        internal static string connectionHelper_LaunchVnc_M2 {
            get {
                return ResourceManager.GetString("connectionHelper_LaunchVnc_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select server list.
        /// </summary>
        internal static string formOptions_bGImport_Click_Select_server_list {
            get {
                return ResourceManager.GetString("formOptions_bGImport_Click_Select_server_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TXT File (*.txt)|*.txt.
        /// </summary>
        internal static string formOptions_bGImport_Click_TXT_File____txt____txt {
            get {
                return ResourceManager.GetString("formOptions_bGImport_Click_TXT_File____txt____txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applying.
        /// </summary>
        internal static string formOptions_bPassword_Click_Applying {
            get {
                return ResourceManager.GetString("formOptions_bPassword_Click_Applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string formOptions_bPassword_Click_Error {
            get {
                return ResourceManager.GetString("formOptions_bPassword_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password can&apos;t be empty.
        /// </summary>
        internal static string formOptions_bPassword_Click_Password_can_t_be_empty {
            get {
                return ResourceManager.GetString("formOptions_bPassword_Click_Password_can_t_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password confirmation doesn&apos;t match.
        /// </summary>
        internal static string formOptions_bPassword_Click_Password_confirmation_doesn_t_match {
            get {
                return ResourceManager.GetString("formOptions_bPassword_Click_Password_confirmation_doesn_t_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select commands file.
        /// </summary>
        internal static string formOptions_bPuTTYExecute_Click_Select_commands_file {
            get {
                return ResourceManager.GetString("formOptions_bPuTTYExecute_Click_Select_commands_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EXE File (*.exe)|*.exe.
        /// </summary>
        internal static string formOptions_bPuTTYPath_Click_EXE_File____exe____exe {
            get {
                return ResourceManager.GetString("formOptions_bPuTTYPath_Click_EXE_File____exe____exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select PuTTY executable.
        /// </summary>
        internal static string formOptions_bPuTTYPath_Click_Select_PuTTY_executable {
            get {
                return ResourceManager.GetString("formOptions_bPuTTYPath_Click_Select_PuTTY_executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select .rdp files path.
        /// </summary>
        internal static string formOptions_bRDKeep_Click_Select__rdp_files_path {
            get {
                return ResourceManager.GetString("formOptions_bRDKeep_Click_Select__rdp_files_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Remote Desktop executable.
        /// </summary>
        internal static string formOptions_bRDPath_Click_Select_Remote_Desktop_executable {
            get {
                return ResourceManager.GetString("formOptions_bRDPath_Click_Select_Remote_Desktop_executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select .vnc files path.
        /// </summary>
        internal static string formOptions_bVNCKeep_Click_Select__vnc_files_path {
            get {
                return ResourceManager.GetString("formOptions_bVNCKeep_Click_Select__vnc_files_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select VNC Viewer executable.
        /// </summary>
        internal static string formOptions_bVNCPath_Click_Select_VNC_Viewer_executable {
            get {
                return ResourceManager.GetString("formOptions_bVNCPath_Click_Select_VNC_Viewer_executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PuTTY private key files (*.ppk)|*.ppk|All files (*.*)|*.*.
        /// </summary>
        internal static string formOptions_bWSCPKey_Click_PuTTY_private_key_files____ppk____ppk_All_files__________ {
            get {
                return ResourceManager.GetString("formOptions_bWSCPKey_Click_PuTTY_private_key_files____ppk____ppk_All_files_______" +
                        "___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select private key file.
        /// </summary>
        internal static string formOptions_bWSCPKey_Click_Select_private_key_file {
            get {
                return ResourceManager.GetString("formOptions_bWSCPKey_Click_Select_private_key_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select WinSCP executable.
        /// </summary>
        internal static string formOptions_bWSCPPath_Click_Select_WinSCP_executable {
            get {
                return ResourceManager.GetString("formOptions_bWSCPPath_Click_Select_WinSCP_executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removing.
        /// </summary>
        internal static string formOptions_cbGPassword_CheckedChanged_Removing {
            get {
                return ResourceManager.GetString("formOptions_cbGPassword_CheckedChanged_Removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List format:
        ///
        ///GroupName  Name     Hostname[:port]     [[Domain\]username]     [Password]     [Type]
        ///
        ///- One server per line.
        ///- Use a tab as separator.
        ///- Only &quot;GroupName&quot; and &quot;Name&quot; are required.
        ///- &quot;Type&quot; is a numerical value, use the following correspondence:
        ///    0 = PuTTY
        ///    1 = Remote Desktop
        ///    2 = VNC
        ///    3 = WinSCP (SCP)
        ///    4 = WinSCP (SFTP)
        ///    5 = WinSCP (FTP)
        ///- If no &quot;Type&quot; is given it&apos;ll be set as &quot;PuTTY&quot; by default..
        /// </summary>
        internal static string formOptions_liGImport_LinkClicked_ {
            get {
                return ResourceManager.GetString("formOptions_liGImport_LinkClicked_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gray_icon {
            get {
                object obj = ResourceManager.GetObject("gray_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greed_icon {
            get {
                object obj = ResourceManager.GetObject("greed_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconadd {
            get {
                object obj = ResourceManager.GetObject("iconadd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icondelete {
            get {
                object obj = ResourceManager.GetObject("icondelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconeyehide {
            get {
                object obj = ResourceManager.GetObject("iconeyehide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconeyeshow {
            get {
                object obj = ResourceManager.GetObject("iconeyeshow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconmodify {
            get {
                object obj = ResourceManager.GetObject("iconmodify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconoptions {
            get {
                object obj = ResourceManager.GetObject("iconoptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_icon {
            get {
                object obj = ResourceManager.GetObject("red_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
