//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPuTTY.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoPuTTY.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closed {
            get {
                object obj = ResourceManager.GetObject("closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeh {
            get {
                object obj = ResourceManager.GetObject("closeh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string connectionHelper_LaunchVnc_Error {
            get {
                return ResourceManager.GetString("connectionHelper_LaunchVnc_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file &quot;.
        /// </summary>
        internal static string connectionHelper_LaunchVnc_M1 {
            get {
                return ResourceManager.GetString("connectionHelper_LaunchVnc_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        ///Do you want to change the configuration ?.
        /// </summary>
        internal static string connectionHelper_LaunchVnc_M2 {
            get {
                return ResourceManager.GetString("connectionHelper_LaunchVnc_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select server list.
        /// </summary>
        internal static string formOptions_bGImport_Click_Select_server_list {
            get {
                return ResourceManager.GetString("formOptions_bGImport_Click_Select_server_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT File (*.txt)|*.txt.
        /// </summary>
        internal static string formOptions_bGImport_Click_TXT_File____txt____txt {
            get {
                return ResourceManager.GetString("formOptions_bGImport_Click_TXT_File____txt____txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying.
        /// </summary>
        internal static string formOptions_bPassword_Click_Applying {
            get {
                return ResourceManager.GetString("formOptions_bPassword_Click_Applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string formOptions_bPassword_Click_Error {
            get {
                return ResourceManager.GetString("formOptions_bPassword_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be empty.
        /// </summary>
        internal static string formOptions_bPassword_Click_Password_can_t_be_empty {
            get {
                return ResourceManager.GetString("formOptions_bPassword_Click_Password_can_t_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation doesn&apos;t match.
        /// </summary>
        internal static string formOptions_bPassword_Click_Password_confirmation_doesn_t_match {
            get {
                return ResourceManager.GetString("formOptions_bPassword_Click_Password_confirmation_doesn_t_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select commands file.
        /// </summary>
        internal static string formOptions_bPuTTYExecute_Click_Select_commands_file {
            get {
                return ResourceManager.GetString("formOptions_bPuTTYExecute_Click_Select_commands_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXE File (*.exe)|*.exe.
        /// </summary>
        internal static string formOptions_bPuTTYPath_Click_EXE_File____exe____exe {
            get {
                return ResourceManager.GetString("formOptions_bPuTTYPath_Click_EXE_File____exe____exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PuTTY executable.
        /// </summary>
        internal static string formOptions_bPuTTYPath_Click_Select_PuTTY_executable {
            get {
                return ResourceManager.GetString("formOptions_bPuTTYPath_Click_Select_PuTTY_executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select .rdp files path.
        /// </summary>
        internal static string formOptions_bRDKeep_Click_Select__rdp_files_path {
            get {
                return ResourceManager.GetString("formOptions_bRDKeep_Click_Select__rdp_files_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Remote Desktop executable.
        /// </summary>
        internal static string formOptions_bRDPath_Click_Select_Remote_Desktop_executable {
            get {
                return ResourceManager.GetString("formOptions_bRDPath_Click_Select_Remote_Desktop_executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select .vnc files path.
        /// </summary>
        internal static string formOptions_bVNCKeep_Click_Select__vnc_files_path {
            get {
                return ResourceManager.GetString("formOptions_bVNCKeep_Click_Select__vnc_files_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select VNC Viewer executable.
        /// </summary>
        internal static string formOptions_bVNCPath_Click_Select_VNC_Viewer_executable {
            get {
                return ResourceManager.GetString("formOptions_bVNCPath_Click_Select_VNC_Viewer_executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PuTTY private key files (*.ppk)|*.ppk|All files (*.*)|*.*.
        /// </summary>
        internal static string formOptions_bWSCPKey_Click_PuTTY_private_key_files____ppk____ppk_All_files__________ {
            get {
                return ResourceManager.GetString("formOptions_bWSCPKey_Click_PuTTY_private_key_files____ppk____ppk_All_files_______" +
                        "___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select private key file.
        /// </summary>
        internal static string formOptions_bWSCPKey_Click_Select_private_key_file {
            get {
                return ResourceManager.GetString("formOptions_bWSCPKey_Click_Select_private_key_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select WinSCP executable.
        /// </summary>
        internal static string formOptions_bWSCPPath_Click_Select_WinSCP_executable {
            get {
                return ResourceManager.GetString("formOptions_bWSCPPath_Click_Select_WinSCP_executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List format:
        ///
        ///GroupName  Name     Hostname[:port]     [[Domain\]username]     [Password]     [Type]
        ///
        ///- One server per line.
        ///- Use a tab as separator.
        ///- Only &quot;GroupName&quot; and &quot;Name&quot; are required.
        ///- &quot;Type&quot; is a numerical value, use the following correspondence:
        ///    0 = PuTTY
        ///    1 = Remote Desktop
        ///    2 = VNC
        ///    3 = WinSCP (SCP)
        ///    4 = WinSCP (SFTP)
        ///    5 = WinSCP (FTP)
        ///- If no &quot;Type&quot; is given it&apos;ll be set as &quot;PuTTY&quot; by default..
        /// </summary>
        internal static string formOptions_liGImport_LinkClicked_ {
            get {
                return ResourceManager.GetString("formOptions_liGImport_LinkClicked_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconadd {
            get {
                object obj = ResourceManager.GetObject("iconadd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icondelete {
            get {
                object obj = ResourceManager.GetObject("icondelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconeyehide {
            get {
                object obj = ResourceManager.GetObject("iconeyehide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconeyeshow {
            get {
                object obj = ResourceManager.GetObject("iconeyeshow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconmodify {
            get {
                object obj = ResourceManager.GetObject("iconmodify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconoptions {
            get {
                object obj = ResourceManager.GetObject("iconoptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
